"""Deterministic explanations and chart suggestions.

The explanation is derived from the SQL syntax tree, not generated by a model: it costs no
tokens, cannot hallucinate, and cannot be hijacked by instructions hidden in the data.
"""
from __future__ import annotations

import sqlglot
from sqlglot import exp

_AGG = {exp.Count: "count of", exp.Sum: "total", exp.Avg: "average", exp.Min: "minimum", exp.Max: "maximum"}


def _clean(node: exp.Expression, dialect: str) -> str:
    return node.sql(dialect=dialect, comments=False).replace('"', "")


def explain_sql(sql: str, dialect: str = "sqlite") -> list[str]:
    """Return short bullet points describing what a SELECT does."""
    try:
        tree = sqlglot.parse_one(sql, read=dialect)
    except Exception:  # noqa: BLE001
        return []
    out: list[str] = []
    ctes = {c.alias_or_name.lower() for c in tree.find_all(exp.CTE)}
    tables = []
    for t in tree.find_all(exp.Table):
        if t.name and t.name.lower() not in ctes and t.name not in tables:
            tables.append(t.name)
    if tables:
        out.append("Reads from " + ", ".join(tables) + (" (joined)" if list(tree.find_all(exp.Join)) else "") + ".")

    sel = tree if isinstance(tree, exp.Select) else tree.find(exp.Select)
    if sel is not None:
        aggs = []
        for node in sel.expressions:
            for agg_cls, label in _AGG.items():
                for a in node.find_all(agg_cls):
                    arg = a.this
                    what = "rows" if isinstance(arg, exp.Star) or arg is None else _clean(arg, dialect)
                    aggs.append(f"{label} {what}")
        if aggs:
            out.append("Computes " + "; ".join(dict.fromkeys(aggs)) + ".")
        where = sel.args.get("where")
        if where is not None:
            out.append("Keeps rows where " + _clean(where.this, dialect) + ".")
        group = sel.args.get("group")
        if group is not None:
            out.append("Grouped by " + ", ".join(_clean(g, dialect) for g in group.expressions) + ".")
        having = sel.args.get("having")
        if having is not None:
            out.append("Keeps groups where " + _clean(having.this, dialect) + ".")
        order = sel.args.get("order")
        if order is not None:
            parts = []
            for o in order.expressions:
                parts.append(_clean(o.this, dialect) + (" descending" if o.args.get("desc") else " ascending"))
            out.append("Sorted by " + ", ".join(parts) + ".")
    limit = tree.args.get("limit")
    if limit is not None:
        out.append(f"Returns at most {limit.expression.name} rows.")
    return out


def suggest_chart(columns: list[str], rows: list[tuple]) -> dict:
    """Pick a sensible visualisation from the shape of a result."""
    if not rows:
        return {"type": "none"}
    if len(rows) == 1 and len(columns) == 1:
        return {"type": "metric", "value": rows[0][0], "label": columns[0]}

    def kind(i: int) -> str:
        vals = [r[i] for r in rows if r[i] is not None]
        if vals and all(isinstance(v, (int, float)) and not isinstance(v, bool) for v in vals):
            return "number"
        if vals and all(isinstance(v, str) and len(v) >= 7 and v[:4].isdigit() and v[4] in "-/" for v in vals):
            return "date"
        return "text"

    kinds = [kind(i) for i in range(len(columns))]
    nums = [i for i, k in enumerate(kinds) if k == "number"]
    if len(columns) == 2 and kinds[0] in ("text", "date") and kinds[1] == "number" and 2 <= len(rows) <= 60:
        return {"type": "line" if kinds[0] == "date" else "bar", "x": columns[0], "y": columns[1]}
    if len(columns) >= 2 and kinds[0] == "date" and nums:
        return {"type": "line", "x": columns[0], "y": [columns[i] for i in nums]}
    return {"type": "table"}
